# SPDX-License-Identifier: Apache-2.0
"""
Kite Logik — governance middleware for enterprise AI agents.

Prerequisite — an OPA engine
----------------------------
``OPAClient`` (default) expects an Open Policy Agent server reachable at
``http://localhost:8181``. The quickest path is::

    docker run -d --name opa -p 8181:8181 -v $(pwd)/policies:/policies \\
        openpolicyagent/opa:latest run --server /policies

Policy files are generated by ``kitelogik init <project>``. For an in-process
alternative that avoids the Docker dependency, use ``RegorusClient`` in place
of ``OPAClient``. Microsoft's Regorus Python bindings must be built from
source — see the ``RegorusClient`` docstring or
https://github.com/microsoft/regorus/tree/main/bindings/python.

Quickstart::

    from kitelogik import AgentSession, OPAClient, PolicyGate, HITLQueue, SessionContext

    opa    = OPAClient()
    gate   = PolicyGate(opa_client=opa)
    queue  = HITLQueue()
    context = SessionContext(session_id="s1", user_role="support_agent",
                             session_scopes=["read_customer"])
    session = AgentSession(gate=gate, context=context, hitl_queue=queue)
    result  = await session.run_async("Look up customer cust_001")

See quickstart.py for a complete working example.
"""

from importlib.metadata import PackageNotFoundError as _PackageNotFoundError
from importlib.metadata import version as _pkg_version

from kitelogik.agents.session import AgentSession, SessionResult
from kitelogik.anchor.credentials import CredentialBroker
from kitelogik.anchor.queue import HITLQueue
from kitelogik.audit.store import AuditStore
from kitelogik.governed import GovernanceError, GovernedToolbox, governed
from kitelogik.memory.models import TrustTier
from kitelogik.memory.store import MemoryStore
from kitelogik.policies.compiler import compile_yaml, compile_yaml_string
from kitelogik.tether.gate import PolicyGate
from kitelogik.tether.hierarchy import HierarchicalEvaluator
from kitelogik.tether.models import (
    PolicyDecision,
    ResolutionStep,
    RiskTier,
    SanitizedResponse,
    SessionContext,
    ToolCallInput,
)
from kitelogik.tether.opa_client import OPAClient, OPAConnectionError
from kitelogik.tether.regorus_client import RegorusClient

try:
    __version__ = _pkg_version("kitelogik")
except _PackageNotFoundError:
    __version__ = "0.0.0-dev"

__all__ = [
    # Version
    "__version__",
    # Zero-restructuring integration
    "governed",
    "GovernedToolbox",
    "GovernanceError",
    # Session execution
    "AgentSession",
    "SessionResult",
    # Policy engine
    "PolicyGate",
    "HierarchicalEvaluator",
    "SessionContext",
    "PolicyDecision",
    "ResolutionStep",
    "RiskTier",
    "SanitizedResponse",
    "ToolCallInput",
    "OPAClient",
    "OPAConnectionError",
    "RegorusClient",
    # Oversight & credentials
    "HITLQueue",
    "CredentialBroker",
    # Audit
    "AuditStore",
    # Memory
    "MemoryStore",
    "TrustTier",
    # Policy compilation
    "compile_yaml",
    "compile_yaml_string",
]
