# SPDX-License-Identifier: Apache-2.0
"""Templates for ``kitelogik init`` scaffolding."""

POLICY_YAML = """\
# Your governance rules. Compiled to Rego (kitelogik.userpolicy) by
# `kitelogik init` and `kitelogik compile`, then aggregated by the core
# bundle alongside the built-in security, delegation, and HITL policies.
version: 1

rules:
  - name: allow_read_ops
    when:
      action:
        - get_customer
        - list_transactions
      scope: read_customer
    then: allow

  - name: allow_small_refund
    when:
      action: approve_refund
      role:
        - support_agent
        - manager
      scope: approve_refund
      args:
        amount:
          lte: 200
    then: allow

  - name: block_large_refund
    when:
      action: approve_refund
      args:
        amount:
          gt: 200
    then: deny
    reason: "Refunds over $200 require manager approval"

  - name: block_shell_access
    when:
      action: run_shell_command
    then: deny
    reason: "Shell access is prohibited"
"""

AGENT_PY = '''\
# SPDX-License-Identifier: Apache-2.0
"""
Governed AI agent — generated by ``kitelogik init``.

Run:
    docker compose up -d             # start OPA policy engine
    python agent.py                  # run governance demo

    ANTHROPIC_API_KEY=sk-... python agent.py   # interactive Claude loop
"""

import asyncio
import os
from pathlib import Path

from kitelogik import (
    GovernanceError,
    GovernedToolbox,
    OPAClient,
    PolicyGate,
    SessionContext,
    compile_yaml,
)

# ── Compile policy & set up governance ───────────────────────────────────────

policy_yaml = Path(__file__).parent / "policies" / "policy.yaml"
policy_rego = policy_yaml.with_suffix(".rego")
policy_rego.write_text(compile_yaml(policy_yaml))
print(f"Compiled {policy_yaml.name} -> {policy_rego}")

gate = PolicyGate(opa_client=OPAClient())
context = SessionContext(
    session_id="session-001",
    user_role="support_agent",
    session_scopes=["read_customer", "approve_refund"],
)

# ── Define tools ─────────────────────────────────────────────────────────────


async def get_customer(customer_id: str) -> str:
    """Look up a customer record by ID."""
    return f"Customer {customer_id}: Acme Corp, plan=enterprise, since=2024"


async def approve_refund(customer_id: str, amount: float) -> str:
    """Process a refund for a customer."""
    return f"Refund of ${amount:.2f} approved for {customer_id}"


# ── Register & run ───────────────────────────────────────────────────────────

toolbox = GovernedToolbox(gate=gate, context=context)
toolbox.register("get_customer", get_customer)
toolbox.register("approve_refund", approve_refund)


async def main():
    print("\\n--- Governance Demo ---\\n")

    calls = [
        ("get_customer", {"customer_id": "cust_001"}),
        ("approve_refund", {"customer_id": "cust_001", "amount": 50.0}),
        ("approve_refund", {"customer_id": "cust_001", "amount": 500.0}),
    ]

    for name, args in calls:
        try:
            result = await toolbox.call(name, args)
            print(f"  ALLOW  {name}({args})")
            print(f"         -> {result}\\n")
        except GovernanceError as e:
            print(f"  BLOCK  {name}({args})")
            print(f"         -> {e}\\n")

    if os.environ.get("ANTHROPIC_API_KEY"):
        print("API key detected. Build your Claude agent loop with toolbox.tool_schemas().")
    else:
        print("Set ANTHROPIC_API_KEY to build an interactive Claude agent.")


if __name__ == "__main__":
    asyncio.run(main())
'''

DOCKER_COMPOSE_YAML = """\
# OPA policy engine for Kite Logik governance.
# Start with: docker compose up -d

services:
  opa:
    image: openpolicyagent/opa:latest
    command: run --server --addr :8181 --watch /policies
    ports:
      - "8181:8181"
    volumes:
      - ./policies:/policies:ro
"""

ENV_EXAMPLE = """\
# Kite Logik environment
# ANTHROPIC_API_KEY=sk-ant-...
"""
